#!/usr/bin/env python3
"""
Data Regeneration & Cleaning Script for Prompt Optimizer
=========================================================

Reads seed, generated, and augmented data; cleans all identified quality issues;
deduplicates on outputs; limits template repetition; splits 80/10/10 with no
output leakage; and saves final datasets.

CRITICAL ISSUES ADDRESSED:
  1. Only 30.7% unique outputs → dedup by output content + near-duplicate trigram overlap
  2. Data leakage (90% of val/test outputs in train) → split groups by output identity
  3. Writing category garbled outputs → filter contradictory length, broken grammar
  4. Placeholder artifacts ("Use none", "-/-/-") → remove
  5. Synthetic "please" insertions → remove items with broken grammar from this
  6. "for for" duplication → remove
  7. Template boilerplate → limit items per structural template to 5

Usage:
    python scripts/regenerate_data.py
"""

import json
import re
import hashlib
import random
from pathlib import Path
from collections import defaultdict
from typing import List, Dict, Tuple, Optional, Set

# ── Configuration ──────────────────────────────────────────────────────────────

SEED_PATH = Path("data/raw/seed_data.jsonl")
GENERATED_PATH = Path("data/raw/generated_data.jsonl")
AUGMENTED_PATH = Path("data/raw/augmented_data.jsonl")

OUTPUT_DIR = Path("data")
TRAIN_RATIO = 0.80
VAL_RATIO = 0.10
TEST_RATIO = 0.10

SEED_RANDOM = 42
MAX_PER_TEMPLATE = 5
MIN_CATEGORY_SIZE = 15
NEAR_DUPLICATE_THRESHOLD = 0.80  # trigram overlap ratio above which outputs are near-duplicates

# ── Helpers ────────────────────────────────────────────────────────────────────

def normalize(text: str) -> str:
    """Lowercase, strip, collapse whitespace."""
    return re.sub(r'\s+', ' ', text.strip().lower())


def trigrams(text: str) -> Set[str]:
    """Extract character trigrams from normalized text."""
    t = normalize(text)
    if len(t) < 3:
        return {t} if t else set()
    return {t[i:i+3] for i in range(len(t) - 2)}


def trigram_similarity(a: str, b: str) -> float:
    """Jaccard similarity on character trigrams."""
    ta, tb = trigrams(a), trigrams(b)
    if not ta and not tb:
        return 1.0
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


def extract_template(output: str) -> str:
    """
    Extract the structural template of an output by:
      1. Replacing specific numbers with N
      2. Replacing quoted phrases with PLACEHOLDER
      3. Replacing proper nouns/topic nouns with PLACEHOLDER
      4. Normalizing whitespace
    The goal is that outputs with the same structural template map to the same string.
    """
    t = output
    # Replace numbers (word counts, etc.)
    t = re.sub(r'\b\d+\.?\d*\b', 'N', t)
    # Replace "X vs Y" comparison patterns
    t = re.sub(r'\bOption [AB]\b', 'OPTION', t)
    # Replace content in parentheses that specifies counts
    t = re.sub(r'\(N[-+]N? words?\)', '(COUNT)', t)
    t = re.sub(r'\(under N words?\)', '(COUNT)', t)
    t = re.sub(r'\(N-N words?\)', '(COUNT)', t)
    # Replace quoted text
    t = re.sub(r'"[^"]*"', '"QUOTE"', t)
    # Normalize whitespace
    t = re.sub(r'\s+', ' ', t.strip())
    return t


def load_jsonl(path: Path) -> List[Dict]:
    """Load a JSONL file, skip empty/malformed lines."""
    items = []
    with open(path) as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
                items.append(item)
            except json.JSONDecodeError:
                print(f"  WARNING: malformed JSON at {path.name}:{line_num}")
    return items


# ── Quality Filters ───────────────────────────────────────────────────────────

def is_garbled_writing(item: Dict) -> bool:
    """
    Detect garbled/contradictory writing outputs.
    
    The writing category was generated by mechanically combining OPTIMIZATION_DIMS
    (length, tone, audience, format, specificity), producing incoherent mashups like:
      "Write a briefly (150-200 words) story ... in detail (1500+ words)"
      "Write a as a short response (under 100 words) guide ..."
      "Write a 500 words essay about AI. in an authoritative tone Focus on..."
    
    Nearly all generated writing outputs suffer from one or more of:
    - Broken sentence structure (period followed by lowercase fragment)
    - Adverb modifying a noun ("Write a comprehensively essay")
    - Contradictory length instructions
    - Unhyphenated compound modifiers ("500 words essay" vs "500-word essay")
    - Format instructions with no verb ("As numbered steps about AI.")
    
    Only keep writing items that read as fluent, coherent English instructions.
    """
    if item["category"] != "writing":
        return False

    output = item["optimized"]

    # ── Hard filters: Always garbled ──

    # Pattern: "Write a as a" — broken grammar from dimension merging
    if re.search(r'\bWrite a as a\b', output):
        return True

    # Pattern: Contradictory length instructions (short + long in same output)
    has_short = bool(re.search(r'briefly|short response|under \d+ words', output, re.I))
    has_long = bool(re.search(r'\bdetail\b|\bcomprehensively\b|1500\+', output, re.I))
    if has_short and has_long:
        return True

    # Pattern: Multiple contradictory word counts
    word_counts = re.findall(r'\b(\d{2,4})\s*words?\b', output)
    if len(word_counts) >= 2:
        counts = [int(w) for w in word_counts]
        if max(counts) > min(counts) * 2:
            return True

    # Pattern: Starts with garbled structure like "As numbered steps about X."
    if re.match(r'^(As|In|Format as)\s', output) and re.search(r'\babout\b', output):
        return True

    # Pattern: Paragraph count + word count (contradictory)
    if 'paragraphs' in output.lower() and re.search(r'\d+\s*words', output):
        return True

    # Pattern: Format instruction with no meaningful verb before the topic
    if re.match(r'^(In|As|Format as)\s', output):
        first_10_words = ' '.join(output.split()[:10])
        if ' about ' in first_10_words.lower() and not any(
            v in first_10_words.lower() for v in ['write', 'create', 'make', 'generate', 'explain', 'describe', 'compose', 'draft']
        ):
            return True

    # ── Structural quality filters: The generated writing data has systematic
    #    grammar problems from the mechanical dimension-combination approach.
    #    These patterns detect the hallmark signs of that broken generation. ──

    # Pattern: Adverb modifying a noun — "Write a comprehensively essay/review/story"
    # "comprehensively", "briefly", "detail" used as adjectives through template filling
    if re.search(r'\bWrite a (briefly|comprehensively|detail|as a short response|as a long)', output, re.I):
        return True
    if re.search(r'^Write a exactly \d+ paragraphs\b', output, re.I):
        return True

    # Pattern: Broken sentence structure — period followed by lowercase fragment
    # This is the signature of the dimension-combination generator which concatenated
    # dimensions with ". " e.g., "Write a 500 words essay about AI. in an authoritative tone"
    # A proper sentence shouldn't have ". in a [tone]" or ". Focus on" etc.
    # We check for: period + space + lowercase word (not a proper noun start)
    if re.search(r'\.\s+(in|for|Focus|as|with|while|maintain|include|prioritize|avoid|structure|use|keep|be)\b', output):
        return True

    # Pattern: Unhyphenated compound modifier before noun — "500 words essay"
    # Proper English: "500-word essay". This is a systematic marker of template filling.
    if re.search(r'\b\d+\s+words?\s+(essay|story|guide|review|article|blog|analysis|opinion|piece|post|report)\b', output, re.I):
        return True

    # Pattern: "about [topic]" at end with fragment before it
    # e.g., "In a narrative style about creativity." — no main verb
    if re.match(r'^(In|As|Format as)\s', output):
        return True

    # Pattern: Double length specification different ways — "briefly (150-200 words)" + "in 500 words"
    if re.search(r'\(\d+[-–]\d+\s*words?\)', output) and re.search(r'in \d+ words\b', output, re.I):
        return True

    return False


def has_placeholder_artifact(item: Dict) -> bool:
    """Check for placeholder artifacts like 'Use none', '-/-/-', 'in none'."""
    output = item["optimized"]
    o_lower = output.lower()

    # "Use none" — from unfilled template slots
    if re.search(r'\buse\s+none\b', o_lower):
        return True
    if re.search(r'\bin\s+none\b', o_lower):
        return True
    if re.search(r'\binclude\s+\w+\s+examples?\s+in\s+none\b', o_lower):
        return True
    # "-/-/-" placeholder
    if '-/-/-' in output:
        return True
    # "for none" or "using none"
    if re.search(r'\b(for|using|with|in)\s+none\b', o_lower):
        return True

    return False


def has_synthetic_please(item: Dict) -> bool:
    """
    Check for grammatically broken "please" insertions.
    Natural: "please help me", "please explain"
    Broken: "teach please me", "guide please for", "compose please a"
    Pattern: <verb> please <pronoun/article> — the "please" is inserted between verb and object.
    """
    vague = item["vague"]
    # Detect patterns like "verb please pronoun" or "verb please article"
    if re.search(r'\b\w+\s+please\s+(me|him|her|us|them|the|a|an|for)\b', vague, re.I):
        return True
    # Also catch "for please" and other broken patterns
    if re.search(r'\bfor\s+please\b', vague, re.I):
        return True
    return False


def has_for_for(item: Dict) -> bool:
    """Check for 'for for' duplication."""
    return "for for" in item["vague"].lower()


# ── Output Deduplication ──────────────────────────────────────────────────────

def deduplicate_outputs(items: List[Dict], seed_outputs: Set[str]) -> List[Dict]:
    """
    Deduplicate by output content:
    1. Exact match on normalized output → keep seed version if available
    2. Near-duplicate via trigram overlap → keep the more detailed one
    """
    # Sort so seed data items come first (they're higher quality)
    # Within same output, prefer items with longer inputs (more specific)
    def sort_key(item):
        is_seed = normalize(item["optimized"]) in seed_outputs
        # Use negative index to sort seeds first; then by output length desc
        return (0 if is_seed else 1, -len(item["optimized"]))

    sorted_items = sorted(items, key=sort_key)

    kept = []
    seen_normalized = {}  # normalized_output -> index in kept

    for item in sorted_items:
        output_norm = normalize(item["optimized"])

        # Check exact match
        if output_norm in seen_normalized:
            # Already have this exact output; skip
            continue

        # Check near-duplicates via trigram similarity
        is_near_dup = False
        output_trigrams = trigrams(item["optimized"])

        if len(output_trigrams) > 5:  # Only check for substantial outputs
            for existing_norm, existing_idx in seen_normalized.items():
                existing_trigrams = trigrams(kept[existing_idx]["optimized"])
                if not existing_trigrams or not output_trigrams:
                    continue

                intersection = len(output_trigrams & existing_trigrams)
                union = len(output_trigrams | existing_trigrams)
                if union == 0:
                    continue

                similarity = intersection / union
                if similarity > NEAR_DUPLICATE_THRESHOLD:
                    is_near_dup = True
                    break

        if not is_near_dup:
            kept.append(item)
            seen_normalized[output_norm] = len(kept) - 1

    return kept


# ── Template Limiting ──────────────────────────────────────────────────────────

def limit_per_template(items: List[Dict], max_per_template: int = MAX_PER_TEMPLATE) -> List[Dict]:
    """
    Group items by their output's structural template and keep at most
    max_per_template items per template. Prefer items with the most
    different/diverse inputs.
    """
    # Group by template
    template_groups = defaultdict(list)
    for item in items:
        template = extract_template(item["optimized"])
        template_groups[template].append(item)

    result = []
    for template, group in template_groups.items():
        if len(group) <= max_per_template:
            result.extend(group)
        else:
            # Select items with the most diverse inputs.
            # Use greedy selection: pick items that maximize input vocabulary diversity.
            selected = []
            input_words_union = set()

            # Sort by input length descending (longer inputs are typically more specific)
            candidates = sorted(group, key=lambda x: -len(x["vague"].split()))

            for item in candidates:
                if len(selected) >= max_per_template:
                    break

                item_input_words = set(normalize(item["vague"]).split())
                # Prefer items that add the most new words to our input vocabulary
                new_words = item_input_words - input_words_union
                if not selected or len(new_words) > 0:
                    selected.append(item)
                    input_words_union |= item_input_words

            # If we still need more items, add from remaining candidates
            for item in candidates:
                if len(selected) >= max_per_template:
                    break
                if item not in selected:
                    selected.append(item)

            result.extend(selected)

    return result


# ── Stratified Split ───────────────────────────────────────────────────────────

def stratified_split_no_leakage(items: List[Dict], train_ratio=TRAIN_RATIO, 
                                  val_ratio=VAL_RATIO, seed=SEED_RANDOM):
    """
    Create stratified 80/10/10 splits ensuring NO output appears in multiple splits.

    Strategy: Group items by their normalized output. All items sharing the same
    output MUST go into the same split. Then distribute these output-groups across
    splits stratified by category.
    """
    rng = random.Random(seed)

    # Group items by normalized output
    output_groups = defaultdict(list)
    for item in items:
        key = normalize(item["optimized"])
        output_groups[key].append(item)

    # Convert to list of groups, each with a representative item and metadata
    groups = []
    for output_key, group_items in output_groups.items():
        # Prefer the item with the longest input (most specific) as representative
        rep = max(group_items, key=lambda x: len(x["vague"]))
        groups.append({
            "output_key": output_key,
            "items": group_items,
            "category": rep["category"],
            "input_len": len(rep["vague"]),
        })

    # Group groups by category
    by_category = defaultdict(list)
    for g in groups:
        by_category[g["category"]].append(g)

    train, val, test = [], [], []

    for cat in sorted(by_category.keys()):
        cat_groups = by_category[cat]
        rng.shuffle(cat_groups)

        n = len(cat_groups)
        n_train = max(1, round(n * train_ratio)) if n > 2 else max(1, n - 2) if n > 2 else n
        n_val = max(1, round(n * val_ratio)) if n > 2 else 1
        n_test = n - n_train - n_val

        # Ensure at least 1 item in each split (if category is big enough)
        if n_test < 1 and n > 2:
            # Steal from train
            n_train -= 1
            n_test += 1
        if n_val < 1 and n > 2:
            n_train -= 1
            n_val += 1

        # If category is too small, put everything in train
        if n <= 2:
            n_train = n
            n_val = 0
            n_test = 0

        train.extend(cat_groups[:n_train])
        val.extend(cat_groups[n_train:n_train + n_val])
        test.extend(cat_groups[n_train + n_val:n_train + n_val + n_test])

    # Flatten
    train_items = [item for g in train for item in g["items"]]
    val_items = [item for g in val for item in g["items"]]
    test_items = [item for g in test for item in g["items"]]

    return train_items, val_items, test_items


# ── Convert to Output Format ───────────────────────────────────────────────────

def to_output_format(item: Dict) -> Dict:
    """Convert from {vague, optimized, category} to {instruction, input, output, category, system}."""
    return {
        "instruction": "Transform the following vague prompt into a clear, specific, and effective prompt:",
        "input": item["vague"],
        "output": item["optimized"],
        "category": item["category"],
        "system": "You are a prompt optimization assistant. Transform vague prompts into clear, specific, well-structured prompts that will elicit better responses from AI models.",
    }


# ── Statistics ─────────────────────────────────────────────────────────────────

def print_stats(label: str, items: List[Dict]):
    """Print comprehensive statistics for a dataset."""
    from collections import Counter

    cats = Counter(item["category"] for item in items)
    outputs = [normalize(item["optimized"]) for item in items]
    unique_outputs = len(set(outputs))

    # Input length stats
    input_lens = [len(item["vague"].split()) for item in items]
    output_lens = [len(item["optimized"].split()) for item in items]

    print(f"\n{'='*60}")
    print(f"  {label}")
    print(f"{'='*60}")
    print(f"  Total items: {len(items)}")
    print(f"  Unique outputs: {unique_outputs} ({100*unique_outputs/max(len(items),1):.1f}%)")
    print(f"  Avg input length: {sum(input_lens)/max(len(input_lens),1):.1f} words")
    print(f"  Avg output length: {sum(output_lens)/max(len(output_lens),1):.1f} words")
    print(f"\n  Per category:")
    for cat in sorted(cats.keys()):
        cat_items = [i for i in items if i["category"] == cat]
        cat_unique = len(set(normalize(i["optimized"]) for i in cat_items))
        print(f"    {cat:16s}: {cats[cat]:4d} items, {cat_unique:4d} unique outputs ({100*cat_unique/max(cats[cat],1):.0f}%)")


# ── Main Pipeline ──────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  PROMPT OPTIMIZER DATA REGENERATION & CLEANING")
    print("=" * 60)

    # ── Step 1: Load all data ──
    print("\n[1/8] Loading raw data...")
    seed_data = load_jsonl(SEED_PATH)
    generated_data = load_jsonl(GENERATED_PATH)
    augmented_data = load_jsonl(AUGMENTED_PATH)

    print(f"  Seed items:      {len(seed_data)}")
    print(f"  Generated items:  {len(generated_data)}")
    print(f"  Augmented items:  {len(augmented_data)}")

    # ── Step 2: Merge and deduplicate identical (vague, optimized, category) triples ──
    print("\n[2/8] Merging and removing exact duplicates...")
    all_items = seed_data + generated_data + augmented_data
    seen_triples = set()
    merged = []
    for item in all_items:
        triple = (normalize(item["vague"]), normalize(item["optimized"]), item["category"])
        if triple not in seen_triples:
            seen_triples.add(triple)
            merged.append(item)

    print(f"  After exact dedup: {len(merged)} (removed {len(all_items) - len(merged)})")

    # ── Step 3: Apply quality filters ──
    print("\n[3/8] Applying quality filters...")

    before_count = len(merged)

    # Track removal reasons
    removal_reasons = defaultdict(int)

    def filter_and_track(items, filter_fn, reason):
        kept, removed = [], []
        for item in items:
            if filter_fn(item):
                removed.append(item)
                removal_reasons[reason] += 1
            else:
                kept.append(item)
        return kept

    # Filter 3a: Remove garbled writing outputs
    merged = filter_and_track(merged, is_garbled_writing, "garbled_writing")

    # Filter 3b: Remove placeholder artifacts
    merged = filter_and_track(merged, has_placeholder_artifact, "placeholder_artifact")

    # Filter 3c: Remove synthetic "please" insertions with broken grammar
    merged = filter_and_track(merged, has_synthetic_please, "broken_please")

    # Filter 3d: Remove "for for" duplication
    merged = filter_and_track(merged, has_for_for, "for_for_duplication")

    # Filter 3e: Remove very short outputs (likely template failures)
    merged = filter_and_track(
        merged,
        lambda item: len(item["optimized"].strip()) < 30,
        "too_short_output"
    )

    # Filter 3f: Remove items where output doesn't reference the input topic
    # (e.g., "Compare Option A vs Option B" for any topic)
    def has_generic_output(item):
        o = item["optimized"]
        # The "Option A vs Option B" template loses the topic entirely
        if re.search(r'Option [AB]\b.*mid-size tech company', o):
            return True
        # Check for completely generic templates that could apply to anything
        # Very short outputs with generic language
        return False

    merged = filter_and_track(merged, has_generic_output, "generic_template")

    print(f"  Filtered: {before_count - len(merged)} items removed")
    for reason, count in sorted(removal_reasons.items(), key=lambda x: -x[1]):
        print(f"    {reason}: {count}")

    # ── Step 4: Output deduplication ──
    print("\n[4/8] Deduplicating by output content...")

    # Build set of seed output norms (to prefer seed data)
    seed_output_norms = set(normalize(item["optimized"]) for item in seed_data)

    before_dedup = len(merged)

    # First pass: exact output dedup (prefer seed, then prefer more detailed)
    merged = deduplicate_outputs(merged, seed_output_norms)

    print(f"  After output dedup: {len(merged)} (removed {before_dedup - len(merged)} duplicates)")
    unique_before = len(set(normalize(i["optimized"]) for i in merged))
    print(f"  Unique outputs: {unique_before}/{len(merged)} ({100*unique_before/max(len(merged),1):.1f}%)")

    # ── Step 5: Template limiting ──
    print("\n[5/8] Limiting template repetition (max {} per template)...".format(MAX_PER_TEMPLATE))

    from collections import Counter
    before_template = len(merged)

    # Apply per-category to preserve category balance
    result_items = []
    cats_present = set(i["category"] for i in merged)
    for cat in cats_present:
        cat_items = [i for i in merged if i["category"] == cat]
        cat_limited = limit_per_template(cat_items, MAX_PER_TEMPLATE)
        result_items.extend(cat_limited)

    merged = result_items
    print(f"  After template limiting: {len(merged)} (removed {before_template - len(merged)})")

    # ── Step 6: Remove small categories ──
    print("\n[6/8] Removing categories with fewer than {} items...".format(MIN_CATEGORY_SIZE))

    cat_counts = Counter(item["category"] for item in merged)
    print(f"  Category distribution before filtering:")
    for cat, count in sorted(cat_counts.items(), key=lambda x: -x[1]):
        status = "KEEP" if count >= MIN_CATEGORY_SIZE else "REMOVE"
        print(f"    {cat:16s}: {count:4d}  [{status}]")

    removed_cats = {cat for cat, count in cat_counts.items() if count < MIN_CATEGORY_SIZE}
    merged = [item for item in merged if item["category"] not in removed_cats]

    if removed_cats:
        print(f"  Removed categories: {removed_cats}")
    else:
        print(f"  No categories removed.")

    # ── Step 7: Final stats before splitting ──
    print_stats("CLEANED DATA (before splitting)", merged)

    # ── Step 8: Stratified split with no output leakage ──
    print("\n[7/8] Creating stratified 80/10/10 split with no output leakage...")

    train, val, test = stratified_split_no_leakage(merged)

    print(f"  Train: {len(train)}")
    print(f"  Val:   {len(val)}")
    print(f"  Test:  {len(test)}")

    # Verify no output leakage
    train_outputs = set(normalize(i["optimized"]) for i in train)
    val_outputs = set(normalize(i["optimized"]) for i in val)
    test_outputs = set(normalize(i["optimized"]) for i in test)

    train_val_leak = train_outputs & val_outputs
    train_test_leak = train_outputs & test_outputs
    val_test_leak = val_outputs & test_outputs

    print(f"\n  LEAKAGE CHECK:")
    print(f"    train ∩ val:   {len(train_val_leak)} shared outputs")
    print(f"    train ∩ test:  {len(train_test_leak)} shared outputs")
    print(f"    val ∩ test:    {len(val_test_leak)} shared outputs")

    if train_val_leak or train_test_leak or val_test_leak:
        print("  WARNING: Output leakage detected! This should not happen.")

    # ── Step 9: Save results ──
    print("\n[8/8] Saving results...")

    for split_name, split_data in [("train", train), ("val", val), ("test", test)]:
        # Save as JSONL
        jsonl_path = OUTPUT_DIR / f"{split_name}.jsonl"
        with open(jsonl_path, 'w') as f:
            for item in split_data:
                f.write(json.dumps(item, ensure_ascii=False) + "\n")
        print(f"  Saved {jsonl_path} ({len(split_data)} items)")

        # Save as JSON
        json_path = OUTPUT_DIR / f"{split_name}.json"
        with open(json_path, 'w') as f:
            json.dump([to_output_format(item) for item in split_data], f, ensure_ascii=False, indent=2)
        print(f"  Saved {json_path}")

    # Save cleaned combined dataset
    cleaned_path = OUTPUT_DIR / "cleaned_data.jsonl"
    with open(cleaned_path, 'w') as f:
        for item in merged:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
    print(f"  Saved {cleaned_path} ({len(merged)} items)")

    # ── Final summary ──
    print("\n" + "=" * 60)
    print("  FINAL SUMMARY")
    print("=" * 60)

    all_split_items = train + val + test
    unique_all = len(set(normalize(i["optimized"]) for i in all_split_items))
    print(f"  Total items: {len(all_split_items)}")
    print(f"  Unique outputs: {unique_all} ({100*unique_all/max(len(all_split_items),1):.1f}%)")
    print(f"  Train: {len(train)} | Val: {len(val)} | Test: {len(test)}")

    cat_counts_final = Counter(item["category"] for item in all_split_items)
    print(f"\n  Final category breakdown:")
    for cat, count in sorted(cat_counts_final.items(), key=lambda x: -x[1]):
        t = sum(1 for i in train if i["category"] == cat)
        v = sum(1 for i in val if i["category"] == cat)
        te = sum(1 for i in test if i["category"] == cat)
        print(f"    {cat:16s}: {count:4d} total  (train={t}, val={v}, test={te})")

    print(f"\n  Pipeline completed successfully!")
    print(f"  Original data: {len(seed_data) + len(generated_data) + len(augmented_data)} items")
    print(f"  Final clean data: {len(all_split_items)} items")
    print(f"  Reduction: {100*(1 - len(all_split_items)/(len(seed_data) + len(generated_data) + len(augmented_data))):.1f}%")


if __name__ == "__main__":
    main()